<style>
    table {
        color: #333;
        width: 800px;
        border-collapse:
        collapse; border-spacing: 0;

    }

    td, th {
        border: 1px solid transparent; /* No more visible border */
        color:#333333;
        border-width: 1px;
        border-color: #a9c6c9;
        border-collapse: collaps
        height: 30px;
        transition: all 0.3s; /* Simple transition for hover effect */
    }

    th {
        background: #DFDFDF; /* Darken header a bit */
        font-weight: bold;
    }

    td {
        background: #FAFAFA;
        text-align: center;
        padding: 10px;
    }


</style>


<!-- Start Slide -->
<section id="slide">
    <div class="sbg">
        <div class="container">
            <h1>Meeting rooms <br>
                Day Offices</h1>
            <h3><br>Configuration<br>Rates<br>Inclusions</h3>
        </div>
    </div><!-- /.sbg -->
</section><!-- /#slide -->
<!-- End Slide -->

<!-- Start contact-us -->
<section id="contact-us">
    <div class="container">
        <div class="contact-us">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="c-txt">
                        <table border="1" CELLPADDING=4 padding="15px" align="center">
                            <tr bgcolor="#dcdcdc">
                                <td><img src="assets/images/offices/1.png"></td>
                                <td><img src="assets/images/offices/2.png"></td>
                                <td><img src="assets/images/offices/3.png"></td>
                                <td><img src="assets/images/offices/4.png"></td>
                                <td><img src="assets/images/offices/5.png"></td>
                                <td><img src="assets/images/offices/6.png"></td>
                                <td><img src="assets/images/offices/7.png"></td>
                            </tr>
                            <tr>
                                <td>Interview room<br>up to 2 people</td>
                                <td>Meeting room <br> up to 4 people</td>
                                <td>Videoconference room <br> up to 4 people</td>
                                <td>Boardroom <br> up to 8 people</td>
                                <td>Private office<br>Consultation room</td>
                                <td>Private office<br>up to 2 people</td>
                                <td>Team room <br>up to 6 people</td>
                            </tr>
                            <tr>
                                <td>$20 per hour<br>$100 per day</td>
                                <td>$40 per hour<br>$200 per day</td>
                                <td>$60 per hour<br>$300 per day</td>
                                <td>$60 per hour<br>$300 per day</td>
                                <td>$25 per hour<br>$150 per day</td>
                                <td>$25 per hour<br>$150 per day</td>
                                <td>$40 per hour<br>$200 per day</td>
                            </tr>
                            <tr>
                                <td colspan="4"> Included: access to kitchen ameneties with filtered water, complimentary tea and coffee (self service), unlimited internet connection, whiteboard, flat screen, TV or projector, break out facilities</td>
                                <td colspan="3"> Included: access to kirchen ameneties wit filtered water, complimentary tea and coffee (self service), unlimited internet connection, break out facilities</td>
                            </tr>
                            <tr>
                                <td colspan="7">SERVICES AVAILABLE AT ADDITIONAL COST: TEA/COFFEE SERVING, WORKING BREAKFAST, LUNCH AND DINNER, ADMIN SUPPORT, STATIONERY, AUDIOCONFERENCING FACILITY.</td>
                            </tr>
                            <tr>
                                <td colspan="7">BOOKINGS OUTSIDE WORKING HOURS, WEEKENDS AND PUBLIC HOLIDAYS ARE SUBJECT TO ADDITIONAL FEE OF $50/HOUR WHICH COVERS COST OF CENTRE TEAM MEMBERS SERVICING BOOKING AIR-CONDITIONING COST.</td>
                            </tr>
                        </table>
                        <br><Br>
                        <div class="au-icon"><button class="btn btn-default hvr-rectangle-in" onclick="window.location.href ='/contactus'">Enquire now</button></div>
                        <br><Br>


                        Or call for more information to: <a href="tel:+612 8378 9100">+612 8378 9100</a>
                        <br><Br>

                    </div>
                </div>
            </div>
        </div>
    </div><!-- container -->
</section><!-- contact-us -->
<!-- End contact-us -->