<style>
    .cuadro1 {
        background: url(../../assets/custom/7.jpeg)no-repeat;
        background-position: 100%;
        background-size: cover;
        overflow:hidden;
        border:2px solid black;
        display: table;
        margin: 0 auto;
        display:table;
        height: 230px;
    }
    .cuadro2 {
         background: url(../../assets/custom/5.jpeg)no-repeat;
         background-position: 100%;
         background-size: cover;
         overflow:hidden;
         border:2px solid black;
         display: table;
         margin: 0 auto;
         float: right;
         height: 230px;
     }
    .cuadro3 {
        background: url(../../assets/custom/2.jpeg)no-repeat;
        background-position: 100%;
        background-size: cover;
        overflow:hidden;
        border:2px solid black;
        display: table;
        margin: 0 auto;
        float: left;
        height: 230px;
    }
    .cuadro4 {
        background: url(../../assets/custom/11.jpeg)no-repeat;
        background-position: 100%;
        background-size: cover;
        overflow:hidden;
        border:2px solid black;
        display: table;
        margin: 0 auto;
        float: right;
        height: 230px;
    }

    .fadeout{
        background-color: rgba(254, 254, 254, 0.74);
        position: relative;
        height: 230px;
    }
    .nopadding {
        padding: 0 !important;
        margin: 0 !important;
    }

    h3 {
        margin-top: 0px !important;
    }
    p {
        margin-bottom: 0px !important;
    }
</style>

<section id="business">
    <div class="container">
        <div class="feature">
            <div class="business">
                <h1>MEETING ROOMS</h1>
                <p class="txt">Have a break from crowded and stressful CBD and schedule your next meeting in Randwick. We offer professional meeting room facilities and our staff are on hand should you require admin support or catering.
                </p>
            </div>
            <div class="b-txt">
                <div class="row" style="margin-bottom: 30px;">
                    <div class="col-md-5 col-sm-4 cuadro1 nopadding">
                        <div class="b-ic fadeout">
                            <div class="b-content">
                                <br>
                                <h3><a href="#">MEETING ROOM</a></h3>
                                <p>$30 per hour<br>
                                $150 per day</p>

                                <p> accommodates up to 4 people</p>

                                <p>  Set up with round table and TV screen, suitable for small meetings, consultations and presentions.
                                </p>
                                <br>
                                <button class="btn btn-default hvr-rectangle-in" onclick="window.location.href ='/contactus'">Enquire now</button>
                                <br>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5 col-sm-4 cuadro2 nopadding">
                        <div class="b-ic fadeout">
                            <div class="b-content">
                                <br>
                                <h3><a href="#">DAY OFFICE</a></h3>
                                <p>$30 per hour<br>
                                 $150 per day</p>

                                <p>   accommodates up to 2-3 people</p>

                                <p>    Set up with desk and visitor chairs or two desks. Ideal for casual office usage or to meet with clients face to face.
                                </p>
                                <br>
                                <button class="btn btn-default hvr-rectangle-in" onclick="window.location.href ='/contactus'">Enquire now</button>
                                <br>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5 col-sm-4 cuadro3 nopadding">
                        <div class="b-ic fadeout">
                            <div class="b-content">
                                <br>
                                <h3><a href="#">BOARDROOM</a></h3>
                                <p>$60 per hour<br>
                                 $300 per day</p>

                                <p>   accommodates up to 10 people</p>

                                <p>   Spacious room with large table, TV screen and whiteboard. Can be configured in class room or U-shape style.
                                </p>
                                <br>
                                <button class="btn btn-default hvr-rectangle-in" onclick="window.location.href ='/contactus'">Enquire now</button>
                                <br>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5 col-sm-4 cuadro4 nopadding">
                        <div class="b-ic fadeout">
                            <div class="b-content">
                                <br>
                                <h3><a href="#">TRAINING ROOM</a></h3>
                                <p>$150 per hour
                                $700 per day</p>

                                <p> accommodates up to 40 people</p>

                                <p> Spacious room ideal for large training group or networking event.
                                </p>
                                <br>
                                <br>
                                <br>
                                <button class="btn btn-default hvr-rectangle-in" onclick="window.location.href ='/contactus'">Enquire now</button>
                                <br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.container -->
</section>