
<!-- Start Slide -->
<section id="slide">
    <div class="sbg">
        <div class="container">
            <h1>Get involved</h1>
            <br><h3>OUR STRATEGY<br>REFERRAL PROGRAM</h3>
        </div>
    </div><!-- /.sbg -->
</section><!-- /#slide -->
<!-- End Slide -->


<!-- Start contact-us -->
<section id="contact-us">
    <div class="container">
        <div class="contact-us">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <div class="c-txt">
                        <p> Anytime Offices has aggresive expansion plans.<br>
                            We believe that our workspace solutions provide vest value for money for any type of business.
                        </p>
                        <p>
                            If you would like to lern more about our strategy please contact Robert on <br><a href="tel:+61477910288"> +61 477 910 288 </a> or email <a href="mailto:robert@anytime-offices.com.au">robert@anytime-offices.com.au <br><br></a>
                        </p>

                        <p>
                            WE WOULD LIKE TO TALK TO
                        </p>
                        <ul>
                            <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>INVESTORS LOOKING FOR EXCITING NEW OPPORTUNITIES</li>
                            <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>LANDLORDS AND PROPERTY OWNERS</li>
                            <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>FRANCHISE CANDIDATES</li>
                            <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>PROPERTY AGENTS</li>
                            <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>INNOVATION ENTHUSIASTS</li>
                            <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>ANYONE WITH INTERESTING IDEAS AND PASSION TO CREATE</li>


                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <form action="/getinvolved" method="post">
                        <div class="c-txt">
                            <h4>Referral details</h4>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Your name" name="name"/>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Company name" name="company"/>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Email" name="email"/>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Mobile" name="mobile"/>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Other instructions" name="other"/>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Name of the person referred" name="namepersonreferred"/>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Company name" name="company2"/>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <select name="" class="form-control"name="enquireabout" >
                                            <option value="">Enquire about</option>
                                            <option value="Office Spaces">Office Spaces</option>
                                            <option value="Virtual Offices">Virtual Offices</option>
                                            <option value="Meeting rooms">Meeting rooms</option>
                                            <option value="Day offices">Day offices</option>
                                        </select>
                                    </div>
                                </div>
                                </br>
                                </br>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <textarea name="message" class="form-control" rows="7" placeholder="message"  name="message"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-default hvr-rectangle-in">submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div><!-- container -->
</section><!-- contact-us -->
<!-- End contact-us -->