
<style>
    .div-image{
        background-image: url('assets/images/shutterstock_229210897.jpg');
        width:100%;
        height:100%;
        z-index: 9997;
    }

    ul, menu, dir {
        display: block;
        list-style-type: disc;
        -webkit-margin-before: 1em;
        -webkit-margin-after: 1em;
        -webkit-margin-start: 0px;
        -webkit-margin-end: 0px;
        -webkit-padding-start: 40px;
    }

    ul>li {
        list-style: none;
        color: #333;
    }
    li {
        display: list-item;
        text-align: -webkit-match-parent;
    }
    .c-txt{
        z-index: 9999;
        color:white;
    }

    #involved-l{
        background-color: rgba(27, 185, 140, 1);
        height:510px;
        color:black;
        line-height: 2.2;
    }

    #involved-r{
        background-color: rgba(34, 47, 63, 1);
        height:510px;
        line-height: 2.2;
    }

    a {color:white;}
    p{margin-top: 10px}

    .hvr-rectangle-in:before {
        background: rgba(34, 47, 63, 1);
    }
</style>

<!-- Start Team -->
<div class="contain">
    <section id="team">
        <div class="team">
            <div class="container">
                <h1 class="title">Get involved</h1>
                <p class="text"> ANYTIME OFFICES HAS AGGRESIVE EXPANSION PLANS. WE BELIEVE THAT OUR WORKSPACE PROVIDE BEST VALUE FOR MONEY FOR ANY TYPE OF BUSINESS.</p>
                <div class="area">

                    <div class="row a-us">
                        <div class="col-md-6 col-sm-6" id="involved-l">
                            <div>
                                <p> Anytime Offices has aggresive expansion plans.<br>
                                    We believe that our workspace solutions provide vest value for money for any type of business.
                                </p>

                                <p>
                                    WE WOULD LIKE TO TALK TO
                                </p>
                                <ul>
                                    <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> INVESTORS LOOKING FOR EXCITING NEW OPPORTUNITIES</li>
                                    <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> LANDLORDS AND PROPERTY OWNERS</li>
                                    <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> FRANCHISE CANDIDATES</li>
                                    <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> PROPERTY AGENTS</li>
                                    <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> INNOVATION ENTHUSIASTS</li>
                                    <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i> ANYONE WITH INTERESTING IDEAS AND PASSION TO CREATE</li>
                                </ul>

                                <p>
                                    If you would like to lern more about our strategy please contact Robert on <br><a href="tel:+61477910288"> +61 477 910 288 </a> or email <a href="mailto:robert@anytime-offices.com.au">robert@anytime-offices.com.au <br><br></a>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6" id="involved-r">
                            <form action="/getinvolved" method="post">
                                <div class="c-txt">
                                    <h4>Referral details</h4>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <input type="text" class="form-control" placeholder="Your name" name="name"/>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <input type="text" class="form-control" placeholder="Company name" name="company"/>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <input type="text" class="form-control" placeholder="Email" name="email"/>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <input type="text" class="form-control" placeholder="Mobile" name="mobile"/>
                                            </div>
                                        </div>
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                <input type="text" class="form-control" placeholder="Other instructions" name="other"/>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="text" class="form-control" placeholder="Name of the person referred" name="namepersonreferred"/>
                                            </div>
                                        </div>
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                <input type="text" class="form-control" placeholder="Company name" name="company2"/>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <select name="" class="form-control"name="enquireabout" >
                                                    <option value="">Enquire about</option>
                                                    <option value="Office Spaces">Office Spaces</option>
                                                    <option value="Virtual Offices">Virtual Offices</option>
                                                    <option value="Meeting rooms">Meeting rooms</option>
                                                    <option value="Day offices">Day offices</option>
                                                </select>
                                            </div>
                                        </div>
                                        </br>
                                        </br>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <textarea name="message" class="form-control" rows="7" placeholder="message"  name="message"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-default hvr-rectangle-in">submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>


                    </div><!-- /.row -->
                </div><!-- /.area -->
            </div><!-- /.container -->
        </div><!-- /.team -->
    </section><!-- /#team -->
    <!-- End Team -->
    <br><br><br>
    <div class="space"></div>





