<style>
    .container2 {
        background-color: #E0E0E0;
        padding-right: 15px;
        padding-left: 15px;
        margin-right: auto;
        margin-left: auto;
    }

    .space {
        margin-top: 30px;
    }
</style>

<!-- Start Team -->
<div class="contain">
    <section id="team">
        <div class="team">
            <div class="container">
                <h1 class="title">WORKSPACES AND PRICING</h1>
                <p class="text">LET US TAKE CARE OF YOUR WORKSPACE NEEDS LEAVING YOU MORE TIME TO DO YOUR WORK AND GROWYOURBUSINESS.</p>
                <div class="area">
                    <div class="row">
                        <div class="col-md-4 col-sm-6">
                            <span style="text-align: center"><h3>OFFICE SPACES</h3></span>
                            <div class="t-box">
                                <div class="t-img">
                                    <img src="assets/images/officessq.jpg" alt="image" />
                                </div>
                                <div class="t-overlay">
                                    <p>Selection of 1 - 10 <br>person offices available.<br>
                                    All monthly expenses associated with traditional office space are taken care of giving you more time to focus on growing your business.<br>
                                   </p></hr>
                                    <h4><a href="/servicesoffices">Read more</a></h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-6">
                            <span style="text-align: center"><h3>VIRTUAL OFFICES</h3></span>
                            <div class="t-box">
                                <div class="t-img">
                                    <img src="assets/images/virtualofficessq.jpg" alt="image" />
                                </div>
                                <div class="t-overlay">
                                    <p>4 virtual office solutions available to help you establish professional business presence. <br>
                                        </p>
                                    <hr />
                                    <div class="content">
                                        <h4><a href="/virtualoffices">Read more</a></h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-6">
                            <span style="text-align: center"><h3>MEETINGS ROOMS</h3></span>
                            <div class="t-box">
                                <div class="t-img">
                                    <img src="assets/images/mettings-rooms.jpg" alt="image" />
                                </div>
                                <div class="t-overlay">
                                    <p>Selection of meeting rooms, interview rooms, boardrooms available to book by the hour or day including after hours and weekends.
                                    <br>
                                    </p>
                                    <hr />
                                    <div class="content">
                                        <h4><a href="/dayoffice">Read more</a></h4>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div><!-- /.row -->
                </div><!-- /.area -->
            </div><!-- /.container -->
        </div><!-- /.team -->
    </section><!-- /#team -->
    <!-- End Team -->
<div class="space"></div>

<!--
<section id="about">
    <div class="about">
        <div class="container">
            <div class="about-us">
                <a name="solutions"></a>
                <h1>OFFICES</h1>
                <p>LET US TAKE CARE OF YOUR WORKSPACE NEEDS GIVING YOU OPPORTUNITY FOCUS ON GROWING.</p>
                <div class="a-us">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="au-img"><img src="assets/images/home-office-1.jpg" alt="image" /></div>
                        </div>
                        <div class="col-md-6">
                            <h5><p>We offer selection of private office suites designed to accommodate 1-10 people.</p></h5>

                            <p>All monthly expenses associated with traditional office space are taken care of giving you more time to focus on growing your business.</p>

                            <p>Our offices are tastefully set up with quality furniture and are equipped with latest technology. You will also benefit from access to kitchen amenities and self-service admin areas. In addition, our team are on hand should you need PA support. OUR .</p>
                            <div class="au-icon"><a href="/servicesoffices">Read more</a></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<section id="about">
    <div class="about">
        <div class="container">
            <div class="about-us">
                <h1>Virtual Offices</h1>
                <div class="a-us">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="au-img"><img src="assets/images/aaaaa.png" alt="image" /></div>
                        </div>
                        <div class="col-md-6">
                            <h5><p>We have a variety of Virtual Office Solutions to suit all budgets and business.</p></h5>

                            <p>We will act as an extension of your business. We can answer your phone calls, handle messages and forward, incoming post required.</p>

                            <p>You will benefit from access to our facilieties including meetings rooms, videoconferencing and day offices and register your businesss address with us.</p>
                            <div class="au-icon"><a href="/virtualoffices">Read more</a></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<section id="about">
    <div class="about">
        <div class="container">
            <div class="about-us">
                <h1>Meetings rooms</h1>
                <div class="a-us">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="au-img"><img src="assets/images/4sacled.png" alt="image" /></div>
                        </div>
                        <div class="col-md-6">
                            <h5><p>We have a selection of meeting room and boardroom facilities available to book.</p></h5>

                            <p>Our rooms are equiped with conferencing equipment and stationary.</p>
                            <p>You are welcome to use our WiFi, kitchen and amenities.</p>
                            <p>You can also order working lunch and tea coffee service.</p>

                            <p>We also have purpose built videoconferencing suite with great accosutics and additional sound proofing.</p>
                            <a href="/dayoffice">Read more</a></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

<section id="about">
    <div class="about">
        <div class="container">
            <div class="about-us">
                <h1>Day Offices</h1>
                <div class="a-us">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="au-img"><img src="assets/images/image8.jpg" alt="image" /></div>
                        </div>
                        <div class="col-md-6">
                            <h5><p>We have a selection of day offices, team rooms and consultation rooms available</p></h5>

                            <p>WiFi and access to kitchen amenities included in rate</p>
                            <p>Our front desk team will meet and great your visitors and will provide support with your admin and catering requirements if required.</p>

                            <a href="/dayoffice">Read more</a></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>-->