

<style>
    .container2 {
        background-color: #E0E0E0;
        padding-right: 15px;
        padding-left: 15px;
        margin-right: auto;
        margin-left: auto;
    }
    table{
        width:100%;
        color:black;
        text-align: center;
    }
    table, th, td {
        border: 1px solid white;
        padding: 5px;
        border-color: white;
    }
    th {
        height: 50px;
        background: rgba(27, 185, 140, 0.7);
        width: 80px;
    }
    tr:nth-child(even) {
        background-color: #f9f9f9;
    }

    tr:nth-child(odd) {
        background-color: #d2d2d2;
    }
    .row {
        margin-right: 0px;
        margin-left: 0px;
        margin-top: ;
    }
    .area2 { margin: 0px 0px 0px 0px}
    .par {
        background: #636363;
        color: white;
        width: 80px;
    }
    .price {font-size: 26px; }
    .first {
        border:none;
    td.firsttd {
        text-align: right;
    }
    h3 {
        margin-top: 0px !important;
    }
</style>

<section id="team-bg">
    <div class="team-bg">
        <div class="container">
            <div class="area">
                <div class="row">
                    <div class="col-md-8 col-sm-3" style="text-align: center; margin: -66px 0px 8px 150px">
                        <h1 style="text-align: center">VIRTUAL OFFICES</h1>
                        <p>Professional business presence for entrepreneurs, mobile professionals, home based businesses and start ups.
                        </p>
                        <button class="btn btn-default hvr-rectangle-in" onclick="window.location.href ='/contactus'">Enquire now</button>
                    </div>
                </div>
            </div>
            <div class="area2">
                <div class="row">
                    <table>
                        <thead>
                        <tr>
                            <th class="first"></th>
                            <th class="par">
                                From<br>
                                <span class="price">$20</span><br>
                                per hour <br>
                                ANYTIME MEETING
                            </th>
                            <th>
                                From<br>
                                <span class="price">$20</span><br>
                                per week <br>
                                ANYTIME MAIL
                            </th>
                            <th class="par">
                                From<br>
                                <span class="price">$20</span><br>
                                per week <br>
                                ANYTIME TELEPHONE
                            </th>
                            <th>
                                From<br>
                                <span class="price">$35</span><br>
                                per week <br>
                                ANYTIME VIRTUAL OFFICE
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td style="text-align: left">Registered business address</td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Mail and Package Handing and forwarding
                            </td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Local fax number
                            </td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Fax to email
                            </td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Local telephone number
                            </td>
                            <td></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">International telephone number
                            </td>
                            <td></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Telephone answering and screening
                            </td>
                            <td></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Call divert</td>
                            <td></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Voicemail</td>
                            <td></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Voicemail to email
                            </td>
                            <td></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Free call forwarding to local numbers
                            </td>
                            <td></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Free call forwarding to national numbers
                            </td>
                            <td></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Free call forwarding to Australian mobile numbers
                            </td>
                            <td></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Private secure letterbox
                            </td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Private storage locker
                            </td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Management of courier services
                            </td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Access to centre facilities
                            </td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Access to admin support and PA services
                            </td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">Access to client directory board
                            </td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td></td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">10% discount on meeting room and day office
                            </td>
                            <td></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                            <td><i class="fa fa-check" aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">2 hours free of meeting room or day office usage
                            </td>
                            <td><i class="fa fa-check" aria-hidden="true"></i> WITH <br>  ANYTIME <br> MEETING 2
                            </td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">4 hours free of meeting room or day office usage
                            </td>
                            <td><i class="fa fa-check" aria-hidden="true"></i> WITH <br>  ANYTIME <br> MEETING 4</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">6 hours free of meeting room or day office usage
                            </td>
                            <td><i class="fa fa-check" aria-hidden="true"></i> WITH  ANYTIME<br>  MEETING 6</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>

                        </tbody>
                    </table>
                </div><!-- /.row -->
            </div>
        </div>
    </div><!-- /.container -->
    </div>
</section>