
<style>

    .pricing {
        margin-top: 50px;
    }

    .pricing ul {
       /* border: 1px solid #e7e7e7;*/
        border-bottom: 0;
        list-style: none;
        padding: 0;
        position: relative;
        top: 0;
        transition: all .3s ease;
        -moz-transition: all .3s ease;
        -webkit-transition: all .3s ease;
        -o-transition: all .3s ease;
    }

    .pricing ul:hover {
        top: -15px;
    }

    .pricing ul li {
        border-bottom: 1px solid #e7e7e7;
        padding: 15px;
    }

    .pricing ul li:nth-child(2n) {
        background: #f8f8f8;
    }

    .pricing .title {
        background: #222;
        border: 0;
        color: #fff;
        font-family: "Montserrat", Arial;
        font-size: 18px;
        font-weight: bold;
        letter-spacing: -0.05em;
        padding: 50px 0 0;
        text-transform: uppercase;
    }

    .pricing .title3 {
        background: #222;
        border: 0;
        color: #fff;
        font-family: "Montserrat", Arial;
        font-size: 10px;
        font-weight: bold;
        text-transform: uppercase;
    }

    .popular .title {
        background: #14b1bb;
    }

    .pricing .price {
        background: #222 !important;
        color: #14b1bb;
        font-family: "Montserrat", Arial;
        font-size: 72px;
        font-weight: bold;
        letter-spacing: -0.05em;

        padding: 0 0 50px;
        text-transform: uppercase;
    }

    .popular .price {
        background: #14b1bb !important;
        color: #222;
    }


</style>


<!-- Start About -->
<section id="about">
    <div class="about">
        <div class="container">
            <div class="about-us">
                <section id="pricing" class="text-center high">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12">
                                <h1>Virtual Offices and Pricing</h1>
                                <h4>Choose a package that fits your needs</h4>
                            </div>
                        </div>
                        <div class="row pricing">
                            <div class="col-sm-3">
                                <ul>
                                    <li class="title">FROM </li>
                                    <li class="price">$17</li>
                                    <li class="title3">per week, excl. GST </li>
                                    <li>BUSINESS ADDRESS </li>
                                    <li>REGISTERED ADDRESS </li>
                                    <li>MAIL AND PACKAGE  HANDLING AND FORWARDING</li>
                                    <li>LOCAL FAX NUMBER</li>
                                    <li>ACCESS TO CENTRE FACILITIES </li>
                                    <li>ACCESS TO ADMIN SUPPORT AND PA SERVICES </li>
                                    <li>ACCESS TO CLIENT DIRECTORY BOARD (AT ADDITIONAL FEE)</li>
                                    <li>DISCOUNT ON MEETING ROOM AND DAY OFFICE BOOKINGS</li>
                                    <li><a href="/register?option=1" class="btn btn-primary">Enquire</a></li>
                                </ul>
                            </div>
                            <div class="col-sm-3">
                                <ul class="popular">
                                    <li class="title">FROM</li>
                                    <li class="price">$23</li>
                                    <li class="title3">per week, excl. GST </li>
                                    <li>LOCAL TELEPHONE NUMBER  </li>
                                    <li>CALL ANSWERING AND SCREENING </li>
                                    <li>CALL DIVERT </li>
                                    <li>VOICEMAIL </li>
                                    <li>LOCAL FAX NUMBER</li>
                                    <li>ACCESS TO CENTRE FACILITIES</li>
                                    <li>ACCESS TO ADMIN SUPPORT AND PA SERVICES </li>
                                    <li>ACCESS TO CLIENT DIRECTORY BOARD (AT ADDITIONAL FEE)</li>
                                    <li>DISCOUNT ON MEETING ROOM AND DAY OFFICE BOOKINGS </li>
                                    <li><a href="/register?option=2" class="btn btn-primary">Enquire</a></li>
                                </ul>
                            </div>
                            <div class="col-sm-3">
                                <ul>
                                    <li class="title">FROM</li>
                                    <li class="price">$40</li>
                                    <li class="title3">per week, excl. GST </li>
                                    <li>BUSINESS ADDRESS </li>
                                    <li>REGISTERED ADDRESS </li>
                                    <li>MAIL AND PACKAGE  HANDLING AND FORWARDING</li
                                    <li>LOCAL TELEPHONE NUMBER  </li>
                                    <li>CALL ANSWERING AND SCREENING </li>
                                    <li>CALL DIVERT </li>
                                    <li>VOICEMAIL </li>
                                    <li>LOCAL FAX NUMBER</li>
                                    <li>ACCESS TO CENTRE FACILITIES</li>
                                    <li>ACCESS TO ADMIN SUPPORT AND PA SERVICES </li>
                                    <li>ACCESS TO CLIENT DIRECTORY BOARD (AT ADDITIONAL FEE)</li>
                                    <li>DISCOUNT ON MEETING ROOM AND DAY OFFICE BOOKINGS </li>
                                    <li><a href="/register?option=3" class="btn btn-primary">Enquire</a></li>
                                </ul>
                            </div>
                            <div class="col-sm-3">
                                <ul class="popular">
                                    <li class="title">FROM</li>
                                    <li class="price">$64</li>
                                    <li class="title3">per week, excl. GST </li>
                                    <li>BUSINESS ADDRESS </li>
                                    <li>REGISTERED ADDRESS </li>
                                    <li>MAIL AND PACKAGE  HANDLING AND FORWARDING</li
                                    <li>LOCAL TELEPHONE NUMBER  </li>
                                    <li>CALL ANSWERING AND SCREENING </li>
                                    <li>CALL DIVERT </li>
                                    <li>VOICEMAIL </li>
                                    <li>LOCAL FAX NUMBER</li>
                                    <li>ACCESS TO CENTRE FACILITIES</li>
                                    <li>ACCESS TO ADMIN SUPPORT AND PA SERVICES </li>
                                    <li>ACCESS TO CLIENT DIRECTORY BOARD (AT ADDITIONAL FEE)</li>
                                    <li>DISCOUNT ON MEETING ROOM AND DAY OFFICE BOOKINGS </li>
                                    <li>FREE DAYS PRIVATE OFFICE USAGE</li>
                                    <li><a href="/register?option=4" class="btn btn-primary">Enquire</a></li>
                                </ul>
                            </div>
                        </div>
                        REGISTRATION FEE - $50 EXCL. GST <br>
                        DEPOSIT – EQUIVALENT TO TWO WEEKS FEE
                    </div>
                </section>
            </div>

        </div>
    </div>
</section>
<!-- End About -->
