
<style>

    .pricing {
        margin-top: 50px;
    }

    .pricing ul {
       /* border: 1px solid #e7e7e7;*/
        border-bottom: 0;
        list-style: none;
        padding: 0;
        position: relative;
        top: 0;
        transition: all .3s ease;
        -moz-transition: all .3s ease;
        -webkit-transition: all .3s ease;
        -o-transition: all .3s ease;
    }

    .pricing ul:hover {
        top: -15px;
    }

    .pricing ul li {
        border-bottom: 1px solid #e7e7e7;
        padding: 15px;
    }

    .pricing ul li:nth-child(2n) {
        background: #f8f8f8;
    }

    .pricing .title {
        background: #222;
        border: 0;
        color: #fff;
        font-family: "Montserrat", Arial;
        font-size: 18px;
        font-weight: bold;
        letter-spacing: -0.05em;
        padding: 50px 0 0;
        text-transform: uppercase;
    }

    .pricing .title3 {
        background: #222;
        border: 0;
        color: #fff;
        font-family: "Montserrat", Arial;
        font-size: 12px;
        font-weight: bold;
        text-transform: uppercase;
    }

    .popular .title {
        background: #14b1bb;
    }

    .pricing .price {
        background: #222 !important;
        color: #14b1bb;
        font-family: "Montserrat", Arial;
        font-size: 72px;
        font-weight: bold;
        letter-spacing: -0.05em;

        padding: 0 0 50px;
        text-transform: uppercase;
    }

    .popular .price {
        background: #14b1bb !important;
        color: #222;
    }


</style>


<!-- Start Slide -->
<section id="slide3">
    <div class="sbg">
        <div class="container">
            <h1>VIRTUAL <br> OFFICES</h1>
            <br><br>
            <h3>OPTIONS<br>BENEFITS <br>PRICING</h3>
        </div>
    </div><!-- /.sbg -->
</section><!-- /#slide -->
<!-- End Slide -->


<!-- Start About -->
<section id="about">
    <div class="about">
        <div class="container">
            <div class="about-us">
                <section id="pricing" class="text-center high">
                    <div class="container">
                        <div class="row pricing">
                            <div class="col-sm-3">
                                <ul>
                                    <li class="title">FROM </li>
                                    <li class="price">$17</li>
                                    <li class="title3">ANYTIME MAIL</li>
                                    <li>REGISTERED ADDRESS </li>
                                    <li>MAIL AND PACKAGE  HANDLING AND FORWARDING</li>
                                    <li>LOCAL FAX NUMBER</li>
                                    <li>ACCESS TO CENTRE FACILITIES </li>
                                    <li>ACCESS TO ADMIN SUPPORT AND PA SERVICES </li>
                                    <li>ACCESS TO CLIENT DIRECTORY BOARD (AT ADDITIONAL FEE)</li>
                                    <li>10% DISCOUNT ON MEETING ROOM AND DAY OFFICE BOOKINGS</li>
                                    <li>PRICE PER WEEK, EXCLUDING GST, REGISTRATION OF $50 AND DEPOSIT OF 2 WEEKS</li>
                                    <li><div class="au-icon"><button class="btn btn-default hvr-rectangle-in" onclick="window.location.href ='/contactus'">Enquire now</button></div></li>
                                </ul>
                            </div>
                            <div class="col-sm-3">
                                <ul class="popular">
                                    <li class="title">FROM</li>
                                    <li class="price">$23</li>
                                    <li class="title3">ANYTIME TELEPHONE </li>
                                    <li>LOCAL TELEPHONE NUMBER  </li>
                                    <li>CALL ANSWERING AND SCREENING </li>
                                    <li>CALL DIVERT </li>
                                    <li>VOICEMAIL </li>
                                    <li>LOCAL FAX NUMBER</li>
                                    <li>ACCESS TO CENTRE FACILITIES</li>
                                    <li>ACCESS TO ADMIN SUPPORT AND PA SERVICES </li>
                                    <li>ACCESS TO CLIENT DIRECTORY BOARD (AT ADDITIONAL FEE)</li>
                                    <li>10% DISCOUNT ON MEETING ROOM AND DAY OFFICE BOOKINGS </li>
                                    <li>PRICE PER WEEK, EXCLUDING GST, REGISTRATION OF $50 AND DEPOSIT OF 2 WEEKS</li>
                                    <li><div class="au-icon"><button class="btn btn-default hvr-rectangle-in" onclick="window.location.href ='/contactus'">Enquire now</button></div></li>
                                </ul>
                            </div>
                            <div class="col-sm-3">
                                <ul>
                                    <li class="title">FROM</li>
                                    <li class="price">$40</li>
                                    <li class="title3">ANYTIME VIRTUAL OFFICE</li>
                                    <li>BUSINESS ADDRESS </li>
                                    <li>MAIL AND PACKAGE  HANDLING AND FORWARDING</li
                                    <li>LOCAL TELEPHONE NUMBER  </li>
                                    <li>CALL ANSWERING AND SCREENING </li>
                                    <li>CALL DIVERT </li>
                                    <li>VOICEMAIL </li>
                                    <li>LOCAL FAX NUMBER</li>
                                    <li>ACCESS TO CENTRE FACILITIES</li>
                                    <li>ACCESS TO ADMIN SUPPORT AND PA SERVICES </li>
                                    <li>ACCESS TO CLIENT DIRECTORY BOARD (AT ADDITIONAL FEE)</li>
                                    <li>10% DISCOUNT ON MEETING ROOM AND DAY OFFICE BOOKINGS </li>
                                    <li>PRICE PER WEEK, EXCLUDING GST, REGISTRATION OF $50 AND DEPOSIT OF 2 WEEKS</li>
                                    <li><div class="au-icon"><button class="btn btn-default hvr-rectangle-in" onclick="window.location.href ='/contactus'">Enquire now</button></div></li>
                                </ul>
                            </div>
                            <div class="col-sm-3">
                                <ul class="popular">
                                    <li class="title">FROM</li>
                                    <li class="price">$64</li>
                                    <li class="title3">ANYTIME VIRTUAL OFFICE PREMIUM</li>
                                    <li>BUSINESS ADDRESS </li>
                                    <li>MAIL AND PACKAGE  HANDLING AND FORWARDING</li
                                    <li>LOCAL TELEPHONE NUMBER  </li>
                                    <li>CALL ANSWERING AND SCREENING </li>
                                    <li>CALL DIVERT </li>
                                    <li>VOICEMAIL </li>
                                    <li>LOCAL FAX NUMBER</li>
                                    <li>ACCESS TO CENTRE FACILITIES</li>
                                    <li>ACCESS TO ADMIN SUPPORT AND PA SERVICES </li>
                                    <li>ACCESS TO CLIENT DIRECTORY BOARD (AT ADDITIONAL FEE)</li>
                                    <li>10% DISCOUNT ON MEETING ROOM AND DAY OFFICE BOOKINGS </li>
                                    <li>5 FREE DAYS PRIVATE OFFICE USAGE</li>
                                    <li>PRICE PER WEEK, EXCLUDING GST, REGISTRATION OF $50 AND DEPOSIT OF 2 WEEKS</li>
                                    <li><div class="au-icon"><button class="btn btn-default hvr-rectangle-in" onclick="window.location.href ='/contactus'">Enquire now</button></div></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </section>
            </div>

        </div>
    </div>
</section>
<!-- End About -->
