<style>
    table {
        color: #333;
        font-family: Helvetica, Arial, sans-serif;
        width: 800px;
        border-collapse:
            collapse; border-spacing: 10px;


    }

    td, th {
        border: 2px solid transparent; /* No more visible border */
        color:#333333;
        border-width: 1px;
        border-color: #a9c6c9;
        border-collapse: collaps
        height: 30px;
        transition: all 0.3s; /* Simple transition for hover effect */
    }

    th {
        background: #DFDFDF; /* Darken header a bit */
        font-weight: bold;
    }

    td {
        background: #FAFAFA;
        text-align: center;
        padding: 10px;
    }

</style>
<!-- Start Slide -->
<section id="slide2">
    <div class="sbg">
        <div class="container">
            <h1>randwick</h1>
            <h3>LOCATION<br>PLACES OF INTEREST<br>CENTRE FEATURES</h3>
        </div>
    </div><!-- /.sbg -->
</section><!-- /#slide -->
<!-- End Slide -->

<!-- Start About -->
<section id="about">
    <div class="about">
        <div class="container">
            <div class="about-us">
                <div class="a-us">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="au-img"><img src="assets/images/randwick-building.jpeg" alt="image" /></div>
                        </div>
                        <div class="col-md-6">
                            <p>ANYTIME OFFICES RANDWICK<br>
                                LEVEL 2 <br>
                                65-71 BELMORE ROAD <br>
                                RANDWICK, NSW 2031 <br>
                            <p/>
                            <p>
                                ANYTIME OFFICES ARE CONVIENIENTLY LOCATED IN RANDWICK’S VIBRANT BELMORE ROAD.
                            </p>
                            <p>
                                OUR CENTRE IS POSITIONED IN THE HEART OF EASTERN SUBURBS NEAR EASTERN BEACHES AND JUST SHORT DRIVE FROM THE AIRPORT AND THE CITY.
                            </p>
                            <div class="au-icon"><button class="btn btn-default hvr-rectangle-in" onclick="window.location.href ='/contactus'">get in touch now</button></div>
                        </div>
                        <div class="col-md-12">
                            <h5>FOR BEACH LOVERS </h5>
                            <p>
                            COOGEE BEACH: 2KM <br>
                            BONDI BEACH:      5.5KM <br>
                            </p>
                            <h5>FOR STUDENTS AND PARENTS</h5>
                            <p>UNIVERSITY OF NSW: 0.7KM <br>
                            OUR LADY OF THE SACRED HEART SCHOOL: 0.4KM <br>
                            COOGEE BOYS PREPARATORY SCHOOL: 0.4KM <br>
                            KENVALLE COLLEGE: 0.6KM <br>
                            RANDWICK LIBRARY: 0.1KM <br>
                            </p>
                            <h5>FOR SPORT AND NATURE LOVERS</h5>
                            <p>SYDNEY CRICKET GROUND: 3.5KM<br>
                            CENTENIAL PARK: 1.5KM</p>

                            <h5>SHOPPING:</h5>
                            <p>
                            ROYAL RANDWICK SHOPPING CENTRE: 0.1KM
                            </p>

                            <h5>NEARBY HOSPITALS</h5>
                            <p>PRINCE OF WALES PRIVATE HOSPITAL: 0.4KM<br>
                            SYDNEY CHILDREN’S HOSPITAL: 0.45KM<br>
                            ROYAL HOSPITAL FOR WOMEN: 1KM</p>

                            <h5>ERRANDS</h5>
                            <p>POST OFFICE: 0.1KM<br>
                            MAJOR BANKS AND ATMS- 0.1-0.5KM<br>
                            RANDWICK PHARMACY: 0.1KM<br>
                            RANDWICK COUNCIL:0.7KM<br>
                            RANDWICK POLICE: 0.3KM</p>




                            <h5>ANYTIME OFFICES RANDWICK OFFERS VARIETY OF WORKSPACE SOLUTIONS INCLUDING:</h5>
                            <p>
                            <ul>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>PRIVATE OFFICES</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>HOT DESKING AND TOUCH DOWN AREAS</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>DAY OFFICES</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>CONSULTATION ROOMS</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>VIDEOCONFERENCING</li>
                            </ul>
                            </p>
                            <p>
                            OUR CENTRE WAS DESIGNED TO SUPPORT CLIENT NEEDS AND PROVIDE EASY AND ACCESSIBLE WORKSPACE.
                            OUR CLIENTS ENJOY QUALITY FIT OUT WITH ADDITIONAL SOUND PROOFING INSTALLED IN WALLS AND CEILINGS, DECENT SIZE FURNITURE AND ENERGY EFFICIENT LIGHTING. <br>
                            </p>
                            <p>
                            WE MADE SURE THAT OUR CENTRE IS EQUIPPED WITH LATEST TECHNOLOGY: <br>
                            <ul>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>WE PROVIDE UNLIMITED HIGH SPEED FIBRE INTERNET CONNECTION WHICH IS SUPPORTED BY CISCO FIREWALL FOR YOUR SECURITY AND ADDITIONAL BACK UP INTERNET LINE SO THAT YOU DON’T LOSE INTERNET ACCESS EVEN DURING THOSE RARE OUTAGES.
                                </li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>WE ALSO MADE PROVISION FOR MODERN TELEPHONY SYSTEM,  VIDEO AND AUDIOCONFERENCING</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>OUR SELF-SERVICE AREAS ARE EQUIPPED WITH MULTI-FUNCTION SCANNER / PHOTOCOPIER / FAX / PRINTER AND IF YOU ONLY NEED COUPLE OF PAGES DONE - WE WILL HAPPILY DO IT AT NO COST</li>
                            </ul>
                            </p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section><!-- /#About -->
<!-- End About -->