<style>
    table {
        color: #333;
        font-family: Helvetica, Arial, sans-serif;
        width: 800px;
        border-collapse:
            collapse; border-spacing: 10px;


    }

    td, th {
        border: 2px solid transparent; /* No more visible border */
        color:#333333;
        border-width: 1px;
        border-color: #a9c6c9;
        border-collapse: collaps
        height: 30px;
        transition: all 0.3s; /* Simple transition for hover effect */
    }

    th {
        background: #DFDFDF; /* Darken header a bit */
        font-weight: bold;
    }

    td {
        background: #FAFAFA;
        text-align: center;
        padding: 10px;
    }

</style>
<!-- Start Slide -->
<section id="slide2">
    <div class="sbg">
        <div class="container">
            <h1>randwick</h1>
            <h3>LOCATION<br>PLACES OF INTEREST<br>CENTRE FEATURES</h3>
        </div>
    </div><!-- /.sbg -->
</section><!-- /#slide -->
<!-- End Slide -->


<!-- Start Map -->
<div id="map" class="ev-map-display"></div>
<!-- End Map -->
</div>

<!-- Start contact-us -->
<section id="contact-us">
    <div class="container">
        <div class="contact-us">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="c-txt">
                        <p> IN THE EASTERN SUBURBS NEAR SYDNEY'S EASTERN BEACHES, ANYTIME OFFICES ARE JUST SHORT DRIVE OR TAXI RIDE FROM THE AIRPORT OR THE CITY.</p>
                        <br><br>
                        <table>
                            <tr>
                                <td>University of New South Wales</td>
                                <td>0.7km</td>
                                <td>Our Lade of the Sacred HEart School</td>
                                <td>0.4km</td>
                                <td>Randwick Council</td>
                                <td>0.7km</td>
                            </tr>
                            <tr>
                                <td>Prince of Wales Private Hospital</td>
                                <td>0.4km</td>
                                <td>Randwich Post Office</td>
                                <td>0.1km</td>
                                <td>Cogee Beach</td>
                                <td>2km</td>
                            </tr>
                            <tr>
                                <td>Prince of Wales Emergency</td>
                                <td>0.6km</td>
                                <td>Randwich Pharmacy</td>
                                <td>0.1km</td>
                                <td>Bondi Beach</td>
                                <td>5.5km</td>
                            </tr>
                            <tr>
                                <td>Randwick Police</td>
                                <td>0.3km</td>
                                <td>Randwick Library</td>
                                <td>0.1km</td>
                                <td>Sydney Cricket Ground</td>
                                <td>3.5km</td>
                            </tr>
                            <tr>
                                <td>Cogee Boys Preparatory School</td>
                                <td>0.4km</td>
                                <td>Royal Hotel Randwick</td>
                                <td>0.5km</td>
                                <td>Allianz Stadium</td>
                                <td>3.9km</td>
                            </tr>
                            <tr>
                                <td>Kenvalle Collegue</td>
                                <td>0.6km</td>
                                <td>Royal Randwick Shopping Centre</td>
                                <td>0.1km</td>
                                <td>Centennial Park</td>
                                <td>1.5km</td>
                            </tr>
                        </table>
                        <br><br>
                        <p>CENTRE FEATURES</p>
                        <br>
                        <table>
                            <tr>
                                <td>22 PRIVATE OFFICES</td>
                                <td>BREAKOUT AREAS</td>
                                <td>GARAGE</td>
                                <td>STORAGE FACILITIES</td>
                            </tr>
                            <tr>
                                <td>SHOWERS</td>
                                <td>HOT DESKING FACILITIES</td>
                                <td>DAILY CLEANING</td>
                                <td>SELF SERVICE ADMIN STATTION</td>
                            </tr>
                            <tr>
                                <td>RECEPTION AND WAITING AREA</td>
                                <td>UNLIMITED HIGH SPEED INTERNET</td>
                                <td>CCTV</td>
                                <td>AIR-CONDIDIONING</td>
                            </tr>
                            <tr>
                                <td>MEETINGS ROOMS</td>
                                <td>MODERN TELEPHONE SYSTEM</td>
                                <td>ON SITE SUPPORT TEAM</td>
                                <td>24/7 ACCESS</td>
                            </tr>
                            <tr>
                                <td>VIDEOCONFERENCING</td>
                                <td>BRAND NEW FIT OUT</td>
                                <td>FULLY EQUIPPEND AND STOCKEN KITCHEN</td>
                                <td>INVOICE</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- container -->
</section><!-- contact-us -->
<!-- End contact-us -->