
<!-- Start Slide -->
<section id="slide3">
    <div class="sbg">
        <div class="container">
            <h1>contact</h1>
           <h3>CONTACT DETAILS<br>ENQUIRY FORM</h3>
        </div>
    </div><!-- /.sbg -->
</section><!-- /#slide -->
<!-- End Slide -->

<!-- Start contact-us -->
<section id="contact-us">
    <div class="container">
        <div class="contact-us">
            <div class="row">
                <div class="col-md-4 col-sm-4">
                    <div class="c-txt">
                        <h3>Contact Us</h3>
                        <ul>
                            <li> <i class="fa fa-map-marker"></i> Visit us: <br>Level 2, 65-71 Belmore Road <br>
                                                                Randwick, NSW 2031<br>
                                                                Australia</li>
                            <li><i class="fa fa-phone"></i>Let's chat between 9am and 6pm weekdays:<br><a href="tel:+612 8378 9100">+612 8378 9100</a></li>
                            <li class="b-c"><i class="fa fa-envelope-o"></i>Email us on: <a href="mailto:info@anytime-offices.com.au">info@anytime-offices.com.au</a></li>
                            <li class="b-c"><i class="fa fa-fax"></i>Fire Up Fax machine - We are litle old school<br>too and love receiving these:<br> +612 8378 9101</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-8 col-sm-8">
                    <form action="/contactus" method="post">
                        <div class="c-txt">
                            <h4>Thanks for your enquiry, you will be contacted shortly.</h4>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div><!-- container -->
</section><!-- contact-us -->
<!-- End contact-us -->



<!-- Start Map -->
<div id="map" class="ev-map-display"></div>
<!-- End Map -->
</div>