<!Doctype html>
<html lang="en" class="no-js">
<head>
    <!-- TITLE OF SITE -->
    <title>Anytime Offices</title>

    <!-- favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="assets/images/favicon.ico">

    <!-- META DATA -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!--font-family-->
    <link href='https://fonts.googleapis.com/css?family=Fira+Sans:300,400,500,700|Libre+Baskerville' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato" />
    <!--font-awesome.min.css-->
    <link href="assets/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>

    <!--smoothbox.css-->
    <link rel="stylesheet" href="assets/css/smoothbox.css">

    <!-- SmartMenus jQuery Bootstrap Addon CSS -->
    <link href="assets/css/jquery.smartmenus.bootstrap.css" rel="stylesheet">

    <!--SLIDER REVOLUTION 4.x CSS SETTINGS-->
    <link rel="stylesheet" href="rs-plugin/css/settings.css" type="text/css" />
    <link rel="stylesheet" href="rs-plugin/css/dynamic-captions.css" type="text/css" />
    <link rel="stylesheet" href="rs-plugin/css/static-captions.css" type="text/css" />

    <!--bootstrap.min.css-->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="assets/css/bootstrap-progressbar.css" rel="stylesheet" type="text/css">

    <!--style.css-->
    <link href="assets/css/style.css" rel="stylesheet" type="text/css"/>

    <!--responsive.css-->
    <link href="assets/css/responsive.css" rel="stylesheet" type="text/css"/>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <script src="animate-legacy-support.js"></script>
    <![endif]-->
</head>


<body>
<!-- Preloader start here -->
<div class="preloader">
    <div class="loader">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
<!-- Preloader end here -->

<!-- Start header -->

    <!-- Start Main-Menu -->
<div id="cabezera">
    <section id="main-menu">

        <section id="header">
            <div class="container">
                <ul class="top-left">
                    <li><i class="fa fa-phone"></i><a href="tel:+612 8378 9100">+612 8378 9100</a></li>
                    <li><i class="fa fa-envelope"></i> <a href="mailto:info@anytime-offices.com.au">info@anytime-offices.com.au</a></li>
                </ul>
                <div class="bc">

                    <div class="h-icon">
                        <div class="icon">
                            <div class="t-bg"><a href="https://www.facebook.com/anytimeoffices/" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></div>
                            <div class="t-bg"><a href="https://twitter.com/AnytimeOffices"  target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></div>
                            <div class="t-bg"><a href="https://www.linkedin.com/company/anytime-offices?trk=biz-companies-cym"  target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a></div>
                            <div class="t-bg"><a href="https://www.instagram.com/officessydney"  target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></div>
                            <div class="t-bg"><a href="https://plus.google.com/+AnytimeOfficesManagementRandwick"  target="_blank"><i class="fa fa-google-plus" aria-hidden="true"></i></a></div>
                            <div class="t-bg"><a href="https://au.pinterest.com/anytimeoffices"  target="_blank"><i class="fa fa-pinterest" aria-hidden="true"></i></a></div>
                        </div>
                    </div>
                </div>
            </div><!-- /.container -->

        </section>

        <div class="container">
            <!-- Navbar -->
            <div class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/#"><img src="assets/images/logo_transparent_background.png" alt="image" /></a>
                </div>
                <div class="navbar-collapse collapse">
                    <!-- right nav -->
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="/">home<span class="sr-only">(current)</span></a></li>
                        <li><a href="#" >solutions <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="/servicesoffices">Offices</a></li>
                                <li><a href="/virtualoffices">Virtual Offices</a></li>
                                <li><a href="/dayoffice">Meeting rooms</a></li>
                                <li><a href="/dayoffice">Day offices</a></li>
                            </ul>
                        </li>
                        <li><a href="/randwick">Randwick</a></li>
                        <li><a href="/getinvolved">Get involved</a></li>
                        <li><a href="/contactus">contact us</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div><!-- /.navbar-default -->
        </div><!-- /.container -->
    </section><!-- /#main-menu -->
    <!-- End Main-Menu -->
</div>

    <div id="contenido">
    <?php echo $this->content; ?>
    </div>

<div id="pie">
    <!-- Start Footer Menu -->
    <section id="f-menu" style="position:absolute">

        <div class="container">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <div class="menu-txt">
                            <p>Copyright 2016   <span>|</span>   Anytime Offices   <span>|</span>   All Rights Reserved.</p>
                        </div>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="active"><a href="/">home<span class="sr-only">(current)</span></a></li>
                            <li><a href="#" >solutions <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/servicesoffices">Offices</a></li>
                                    <li><a href="/virtualoffices">Virtual Offices</a></li>
                                    <li><a href="/dayoffice">Meeting rooms</a></li>
                                    <li><a href="/dayoffice">Day offices</a></li>
                                </ul>
                            </li>
                            <li><a href="/randwick">Randwick</a></li>
                            <li><a href="/getinvolved">Get involved</a></li>
                            <li><a href="/contactus">contact us</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav><!-- .navbar navbar-default -->
            <!-- scroll-to-top -->
            <div class="scroll-to-top">
                <a href="#" id="scrollup"><i class="fa fa-angle-up"></i></a>
            </div>
            <!-- scroll-to-top -->
        </div><!-- /.container -->
    </section><!-- /#f-menu -->
</div>
<!-- End Footer Menu -->



<!--jquery,bootstrap-->
<script src="assets/js/jquery-1.11.3.min.js" type="text/javascript"></script>
<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.js"></script>

<!-- SmartMenus jQuery plugin/jQuery Bootstrap Addon -->
<script type="text/javascript" src="assets/js/jquery.smartmenus.js"></script>
<script type="text/javascript" src="assets/js/jquery.smartmenus.bootstrap.js"></script>

<!--Isotope JS-->
<script src="assets/js/imagesloaded.pkgd.min.js"></script>
<script src="assets/js/isotope.function.js" type="text/javascript"></script>
<script src="assets/js/isotope.pkgd.min.js" type="text/javascript"></script>

<!-- smoothbox JS file -->
<script type="text/javascript" src="assets/js/smoothbox.min.js"></script>

<!--SLIDER REVOLUTION 4.x SCRIPTS-->
<script type="text/javascript" src="rs-plugin/js/jquery.themepunch.tools.min.js"></script>
<script type="text/javascript" src="rs-plugin/js/jquery.themepunch.revolution.min.js"></script>

<!-- Bootstrap-progress-bar -->
<script type="text/javascript" src="assets/js/bootstrap-progressbar.js"></script>

<!--gmaps-->
<script src="http://maps.google.com/maps/api/js?key=AIzaSyDdhHmow9z7lmpRnAXDThXjr1ioje7LPTg"></script>
<script src="assets/js/gmaps.js"></script>

<!--Custom JS-->
<script src="assets/js/custom.js" type="text/javascript"></script>

</body>
</html>