<!Doctype html>
<html lang="en" class="no-js">
<head>
    <!-- TITLE OF SITE -->
    <title>Anytime Offices</title>

    <!-- favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">

    <!-- META DATA -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!--font-family-->
    <link href='https://fonts.googleapis.com/css?family=Fira+Sans:300,400,500,700|Libre+Baskerville' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato" />
    <!--font-awesome.min.css-->
    <link href="assets/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>

    <!--smoothbox.css-->
    <link rel="stylesheet" href="assets/css/smoothbox.css">

    <!-- SmartMenus jQuery Bootstrap Addon CSS -->
    <link href="assets/css/jquery.smartmenus.bootstrap.css" rel="stylesheet">

    <!--SLIDER REVOLUTION 4.x CSS SETTINGS-->
    <link rel="stylesheet" href="rs-plugin/css/settings.css" type="text/css" />
    <link rel="stylesheet" href="rs-plugin/css/dynamic-captions.css" type="text/css" />
    <link rel="stylesheet" href="rs-plugin/css/static-captions.css" type="text/css" />

    <!--bootstrap.min.css-->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="assets/css/bootstrap-progressbar.css" rel="stylesheet" type="text/css">

    <!--style.css-->
    <link href="assets/css/style.css" rel="stylesheet" type="text/css"/>

    <!--responsive.css-->
    <link href="assets/css/responsive.css" rel="stylesheet" type="text/css"/>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <script src="animate-legacy-support.js"></script>
    <![endif]-->
    <script type="text/javascript" src="js/cssrefresh.js"></script>
    <style>

        .homemenu{
            background:#222;
        }
        .homemenu2{
            background:white;
        }
        .menubox{
            border-color: white;
            border-width: 3px;
            height: 80px;
            text-align: center;
            vertical-align: middle;
            border-style: solid;

        }

        .menubox h3{
            font-size: 20px;
            color: white;
        }

        .menubox2{
            text-align: center;

        }

        .menubox2 h4{
            font-size: 16px;
            color: black;
        }

        a {
            color: #2e2e2e;
            text-decoration: none;
        }
        a:hover {
            color: #7b7b7b;
        }

    </style>
</head>


<body>
<!-- Preloader start here -->
<div class="preloader">
    <div class="loader">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
<!-- Preloader end here -->

<!-- Start header -->
<div class="contain">


    <section id="header">
        <div class="container">
            <ul class="top-left">
                <li><i class="fa fa-phone"></i><a href="tel:+612 8378 9100">+612 8378 9100</a></li>
                <li><i class="fa fa-envelope"></i> <a href="mailto:info@anytime-offices.com.au"><span style="text-transform: lowercase;">info@anytime-offices.com.au</span></a></li>
            </ul>
            <div class="bc">

                <div class="h-icon">
                    <div class="icon">
                        <div class="t-bg"><a href="https://www.facebook.com/anytimeoffices/" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></div>
                        <div class="t-bg"><a href="https://twitter.com/AnytimeOffices" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></div>
                        <div class="t-bg"><a href="https://www.linkedin.com/company/anytime-offices?trk=biz-companies-cym" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a></div>
                        <div class="t-bg"><a href="https://www.instagram.com/officessydney" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></div>
                        <div class="t-bg"><a href="https://plus.google.com/+AnytimeOfficesManagementRandwick" target="_blank"><i class="fa fa-google-plus" aria-hidden="true"></i></a></div>
                        <div class="t-bg"><a href="https://au.pinterest.com/anytimeoffices" target="_blank"><i class="fa fa-pinterest" aria-hidden="true"></i></a></div>
                    </div>
                </div>
            </div>
        </div><!-- /.container -->

    </section>

        <!-- Start Main-Menu -->
    <section id="main-menu">
        <div class="container">
            <!-- Navbar -->
            <div class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/#"><img src="assets/images/logo_transparent_background.png" alt="image" /></a>
                </div>
                <div class="navbar-collapse collapse">
                    <!-- right nav -->
                    <ul class="nav navbar-nav">
                        <!--<li class="active">-->
                        <li><a href="/">home<span class="sr-only">(current)</span></a></li>
                        <li><a href="#" >Workspaces & Pricing<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="/servicesoffices" class="logo">Office Space</a></li>
                                <li><a href="/virtualoffices">Virtual Office</a></li>
                                <li><a href="/dayoffice">Meeting room</a></li>
                            </ul>
                        </li>
                        <li><a href="/randwick">Randwick</a></li>
                        <li><a href="/getinvolved">Get involved</a></li>
                        <li><a href="/contactus">contact us</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div><!-- /.navbar-default -->
        </div><!-- /.container -->
    </section><!-- /#main-menu -->
    <!-- End Main-Menu -->

    <?php echo $this->content; ?>

    <!--End slider section-->
    <section>
        <div class="homemenu">
            <div class="row">
                <div class="col-md-3 menubox"><br><h3><a href="/workspace" class="menu">WORKSPACE <br>AND PRICING</a></h3></div>
                <div class="col-md-3 menubox"><br><h3><a href="/randwick" class="menu">RANDWICK</a></h3></div>
                <div class="col-md-3 menubox"><br><h3><a href="/getinvolved" class="menu">GET INVOLVED</a></h3></div>
                <div class="col-md-3 menubox"><br><h3><a href="/contactus" class="menu">CONTACT US</a></h3></div>
            </div>
        </div>
    </section>
    <section>
        <div class="homemenu2">
            <div class="row">
                <div class="col-md-3 menubox2">
                    <span><h5>WORKSPACE & PRICING</h5></span>
                    <span><h5><a href="/servicesoffices" class="link">Office space</a></h5></span>
                    <span><h5><a href="/virtualoffices" class="link">Virtual Office</a></h5></span>
                    <span><h5><a href="/dayoffice" class="link">Meeting Room</a></h5></span>

                </div>
                <div class="col-md-3 menubox2">
                    <span><h5>RANDWICK</h5></span>
                    <span><h5><a href="/randwick" class="link">Location</a></h5></span>
                    <span><h5><a href="/#" class="link">Centre Features</a></h5></span></div>
                <div class="col-md-3 menubox2">
                    <span><h5>GET INVOLVED</h5></span>
                    <span><h5><a href="/contactus" class="link">Contact details</a></h5></span>
                    <span><h5><a href="/#" class="link">Referral program</a></h5></span>
                </div>
                <div class="col-md-3 menubox2">
                    <span><h5>CONTACT US</h5></span>
                    <span><a href="/privacy" class="link"><h5>Privacy Policy</a></h5></span>
                    <img src="assets/images/logo-green.gif" width="75">
                </div>
            </div>
        </div>
    </section>

    <!-- Start Footer Menu -->
    <section id="f-menu">
        <div class="container">
            <nav class="navbar navbar-default">
                <div class="container-fluid">

                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <div class="menu-txt">
                            <p>Copyright 2012 - 2016   <span>|</span>   Every Templates   <span>|</span>   All Rights Reserved. | <a href="/privacy"> Privacy Policy </a></p>
                        </div>
                    </div>

                </div><!-- /.container-fluid -->
            </nav><!-- .navbar navbar-default -->
            <!-- scroll-to-top -->
            <div class="scroll-to-top">
                <a href="#" id="scrollup"><i class="fa fa-angle-up"></i></a>
            </div>
            <!-- scroll-to-top -->
        </div><!-- /.container -->
    </section><!-- /#f-menu -->
    <!-- End Footer Menu -->

</div>
<!-- End Footer Menu -->



<!--jquery,bootstrap-->
<script src="assets/js/jquery-1.11.3.min.js" type="text/javascript"></script>
<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.js"></script>

<!-- SmartMenus jQuery plugin/jQuery Bootstrap Addon -->
<script type="text/javascript" src="assets/js/jquery.smartmenus.js"></script>
<script type="text/javascript" src="assets/js/jquery.smartmenus.bootstrap.js"></script>

<!--Isotope JS-->
<script src="assets/js/imagesloaded.pkgd.min.js"></script>
<script src="assets/js/isotope.function.js" type="text/javascript"></script>
<script src="assets/js/isotope.pkgd.min.js" type="text/javascript"></script>

<!-- smoothbox JS file -->
<script type="text/javascript" src="assets/js/smoothbox.min.js"></script>

<!--SLIDER REVOLUTION 4.x SCRIPTS-->
<script type="text/javascript" src="rs-plugin/js/jquery.themepunch.tools.min.js"></script>
<script type="text/javascript" src="rs-plugin/js/jquery.themepunch.revolution.min.js"></script>

<!-- Bootstrap-progress-bar -->
<script type="text/javascript" src="assets/js/bootstrap-progressbar.js"></script>

<!--gmaps-->
<script src="http://maps.google.com/maps/api/js?key=AIzaSyDdhHmow9z7lmpRnAXDThXjr1ioje7LPTg"></script>
<script src="assets/js/gmaps.js"></script>

<!--Custom JS-->
<script src="assets/js/custom.js" type="text/javascript"></script>

</body>
</html>