
<!-- Start Slide -->
<section id="slide3">
    <div class="sbg">
        <div class="container">
            <h1>contact</h1>
           <!-- <h3>LOCATION<br>PLACES OF INTEREST<br>CENTRE FEATURES</h3> -->
        </div>
    </div><!-- /.sbg -->
</section><!-- /#slide -->
<!-- End Slide -->

<!-- Start contact-us -->
<section id="contact-us">
    <div class="container">
        <div class="contact-us">
            <div class="row">
                <div class="col-md-4 col-sm-4">
                    <div class="c-txt">
                        <h3>Contact Us</h3>
                        <p> You can contact or visit us in our office from Monday to Friday from 8:00 - 17:00</p>
                        <ul>
                            <li> <i class="fa fa-map-marker"></i> Level 2, 65-71 Belmore Road <br>
                                                                Randwick, NSW 2031<br>
                                                                Australia</li>
                            <li><i class="fa fa-phone"></i>Let's chat between 9am and 6pm weekdays:<br>+612 8378 9100</li>
                            <li class="b-c"><i class="fa fa-envelope-o"></i><a href="#">info@anytime-offices.com.au</a></li>
                            <li class="b-c"><i class="fa fa-envelope-o"></i><a href="#">Fire Up Fax machine - We are litle old school<br>
                                                                                        too and love receiving these:<br> +612 8378 9101</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-8 col-sm-8">
                    <form>
                        <div class="c-txt">
                            <h4>ENQUIRY FORM</h4>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="name"/>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Company name"/>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Email"/>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Mobile"/>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <select name="" class="form-control" >
                                            <option>Enquire about</option>
                                            <option>Office Spaces</option>
                                            <option>Virtual Offices</option>
                                            <option>Meeting rooms</option>
                                            <option>Day offices</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <textarea name="message" class="form-control" rows="7" placeholder="message"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-default hvr-rectangle-in">submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div><!-- container -->
</section><!-- contact-us -->
<!-- End contact-us -->



<!-- Start Map -->
<div id="map" class="ev-map-display"></div>
<!-- End Map -->
</div>