
    <section id="contact-us">
        <div class="container">
            <h1 class="title">CONTACT US</h1>

            <div class="contact-us">
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <form action="/contactus" method="post">
                            <div class="c-txt">
                                <h4>ENQUIRY FORM</h4>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="Your name" name="name">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="Company name" name="company">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="Email" name="email">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="Mobile" name="mobile">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <select name="type" class="form-control">
                                                <option value="">Enquire about</option>
                                                <option value="Office Spaces">Office Spaces</option>
                                                <option value="Virtual Offices">Virtual Offices</option>
                                                <option value="Meeting rooms">Meeting rooms</option>
                                                <option value="Day offices">Day offices</option>
                                            </select>
                                        </div>
                                        <br>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <textarea name="message" class="form-control" rows="7" placeholder="message"></textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-default hvr-rectangle-in">submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div style="margin-top:30px;"></div>
                <div class="row">
                    <div class="col-md-4 col-sm-4">
                        <div class="c-txt">
                            <ul>
                                <li><i class="fa fa-map-marker"></i> Visit us: <br>Level 2, 65-71 Belmore Road <br>
                                    Randwick, NSW 2031<br>
                                    Australia</li>
                                <li><i class="fa fa-phone"></i>Let's chat between 9am and 6pm weekdays:<br><a href="tel:+612 8378 9100">+612 8378 9100</a></li>
                                <li class="b-c"><i class="fa fa-envelope-o"></i> Email us on: <a href="mailto:info@anytime-offices.com.au">info@anytime-offices.com.au</a></li>
                                <li class="b-c"><i class="fa fa-fax"></i> Fire Up Fax machine - We are litle old school<br>too and love receiving these:<br> +612 8378 9101</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-8 col-sm-8">
                            <div id="map" class="ev-map-display"></div>
                        </div>

                    <div>
                </div>
            </div>
        </div><!-- container -->
    </section>

