<style>
    .container2 {
        background-color: #E0E0E0;
        padding-right: 15px;
        padding-left: 15px;
        margin-right: auto;
        margin-left: auto;
    }
</style>

<!-- Start Slide -->
<section id="slide">
    <div class="sbg">
        <div class="container">
            <h1>Services Offices</h1>
            <h3>Benefits of serviced office rate by<br>ANYTIME OFFICES</h3>
        </div>
    </div><!-- /.sbg -->
</section><!-- /#slide -->
<!-- End Slide -->

<!-- Start About -->
<section id="about">
    <div class="about">
        <div class="container">
                <div class="a-us">
                    <div class="row">
                        <div class="col-md-12">
                            <p>We offer selection of private office suites designed to accommodate 1-10 people.</p>
                            <p>All monthly expenses associated with traditional office space are taken care of giving you more time to focus on growing your business.</p>
                            <p>Our offices are tastefully set up with quality furniture and are equipped with latest technology. You will also benefit from access to kitchen amenities and self-service admin areas. In addition, our team are on hand should you need PA support. OUR                            <ul>
                        </div>
                        <div class="col-md-6">
                            <ul>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>OFFICE RENT</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>FURNITURE</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>UTILITY BILLS (ELECTRICITY, GAS, WATER) </li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>DAILY CLEANING</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>SECURITY</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>24/7 ACCESS</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>BUILDING OUTGOINGS / STRATA FEES</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>UNLIMITED INTERNET</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>ACCESS TO KITCHEN AMENITIES WITH FREE GROUND COFFEE AND ASSORTED TEA</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>OFFICE FIT OUT</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>INFRASTRUCTURE COST (POWER AND DATA INSTALLATION, COMMUNICATION ROOM etc.)</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>BREAK OUT AREAS AND COMMON AREAS</li>
                                </ul>
                        </div>
                        <div class="col-md-6">
                            <ul>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>RECEPTION AND WAITING AREA</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>ACCESS TO MEETING ROOMS</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>CORPORATE IDENTITY AND IMAGE (LISTING ON CLIENT DIRECTORY BOARD AND POSSIBILITY OF CUSTOMISING OFFICE WITH COMPANY LOGO etc.)</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>ONE SIMPLE INVOICE</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>2 WEEKS PAYMENT TERMS</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>LOW ENTRY COST (6 WEEKS DEPOSIT AND SMALL SET UP FEE)</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>LOW EXIT COST</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>BUSINESS CONTINUITY WHEN MOVING OUT</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>FLEXIBLE TERMS WITH DAILY AND MONTHLY RATES AVAILABLE</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>BUSINESS SUPPORT AND PA SERVICES</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>DAILY MAIL DELIVERY AND COLLECTION</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>CORPORATE DISCOUNTS AND SPECIAL TERMS WITH SEVERAL SERVICE PROVIDERS (COURIERS, STATIONERY, FURNITURE etc)</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>BUILDING MAINTENANCE AND HANDYMAN SERVICES</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>AIR-CONDITIONING IN BUSINESS HOURS</li>
                                <li><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>CENTRE EVENTS AND NETWORKING OPPORTUNITIES</li>
                                </ul>
                            </div>
                        <div class="au-icon"><button class="btn btn-default hvr-rectangle-in" onclick="window.location.href ='/contactus'">Enquire now</button></div>
                        <br><Br>
                        </div>

                    </div>
            </div>

        </div>
    </div>
</section><!-- /#About -->