<section id="team-bg">
    <div class="team-bg">
        <div class="container">
            <div class="area">
                <div class="row">
                    <div class="col-md-8 col-sm-4" style="text-align: center; margin: -66px 0px 8px 150px">
                        <h1 style="text-align: center">OFFICE SPACES</h1>
                        <p>Various sizes private serviced offices available for lease.
                            Flexible office rental terms, transparent pricing and affordable rates to suit any budget.
                            From $30 per hour / $150 per day on casual basis
                            Or from $100 per person per week on ongoing basis.
                        </p>
                        <button class="btn btn-default hvr-rectangle-in" onclick="window.location.href ='/contactus'">Enquire now</button>
                    </div>
                </div>
            </div>
            <div >
                <div class="row">
                    <div class="col-md-4 col-sm-4">
                        <div class="s-box">
                            <div class="s-icon">
                                <div class="s-ibg"></div>
                                <i class="fa fa-code" aria-hidden="true"></i>
                            </div>
                            <div class="s-content">
                                <h4><a href="#">WORKSPACE</a></h4>
                                <p>24/7 ACCESS<br>
                                    OFFICE RENTAL<br>
                                    RECEPTION AND COMMON AREA<br>
                                    BREAK OUT AREAS<br>
                                    KITCHEN AMENITIES<br>
                                    BATHROOMS WITH SHOWERS<br>
                                    PARKING<br>
                                    MEETING ROOMS AND CASUAL OFFICES<br>
                                    STORAGE FACILITIES</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="s-box">
                            <div class="s-icon">
                                <div class="s-ibg"></div>
                                <i class="fa fa-leaf" aria-hidden="true"></i>
                            </div>
                            <div class="s-content">
                                <h4><a href="#">FACILITIES
                                    </a></h4>
                                <p>FURNITURE<br>
                                    DAILY CLEANING<br>
                                    ELECTRICITY<br>
                                    PROPERTY CHARGES<br>
                                    UTILITIES<br>
                                    SECURITY<br>
                                    REGULR MAINTENANCE<br>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="s-box">
                            <div class="s-icon">
                                <div class="s-ibg"></div>
                                <i class="fa fa-random" aria-hidden="true"></i>
                            </div>
                            <div class="s-content">
                                <h4><a href="#">TECHNOLOGY
                                    </a></h4>
                                <p>UNLIMITED FAST SPEED INTERNET<br>
                                    SECOND INTERNET CONNECTION<br>
                                    SECURE WIFI THROUGHOUT<br>
                                    SELF SERVICE ADMIN STATION<br>
                                    MODERN TELEPHONE SYSTEM<br>
                                    VIDEOCONFERENCING<br>
                                    CLIENT PORTAL</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="s-box">
                            <div class="s-icon">
                                <div class="s-ibg"></div>
                                <i class="fa fa-wordpress" aria-hidden="true"></i>
                            </div>
                            <div class="s-content">
                                <h4><a href="#">SUPPORT
                                    </a></h4>
                                <p>RECEPTION SUPPORT<br>
                                    TELEPHONE ANSWERING<br>
                                    MAIL HANDLING<br>
                                    ADMIN SUPPORT<br>
                                    PA SERVICES<br>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="s-box">
                            <div class="s-icon">
                                <div class="s-ibg"></div>
                                <i class="fa fa-life-ring" aria-hidden="true"></i>
                            </div>
                            <div class="s-content">
                                <h4><a href="#">TRANPARENCY</a></h4>
                                <p>SIMPLE ONE PAGE TERMS AND CONDITIONS<br>
                                    TRANSPARENT PRICING<br>
                                    ALL INCLUSIVE PACKAGES AND NO HIDDEN COST<br>
                                    FLEXIBLE TERMS<br>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="s-box">
                            <div class="s-icon">
                                <div class="s-ibg"></div>
                                <i class="fa fa-codiepie" aria-hidden="true"></i>
                            </div>
                            <div class="s-content">
                                <h4><a href="#">WHAT MAKES US DIFFERENT
                                    </a></h4>
                                <p>ADDITIONAL SOUND PROFING IN THE WALLS AND CEILING<br>
                                    UNLIMITED INTERNET; <br>
                                    TWO INDEPENDENT IT LINES INTERNET LINES<br>
                                    PRIVATE LETTER BOXES FOR VIRTUAL CLIENTS<br>
                                    BILLING, ACCOUNTING AND CLIENT QUERIES ARE MANAGED ON SITE AND IN TIMELY FASHION<br>
                                    COFFEE TASTES LIKE COFFEE<br>
                                </p>
                            </div>
                        </div>
                    </div>
                </div><!-- /.row -->
            </div>
        </div>
    </div><!-- /.container -->
    </div>
</section>
