
<style>
    container {text-align: right;}
</style>
<!-- Start About -->
<section id="about">
    <div class="about">
        <div class="container">
            <div class="about-us">
                <section class="high">
                    <div class="container">
                        <h3>Privacy Policy of Anytime Offices</h3>
                        <br>
                        <h4>Information about our organization and websites</h4>
                        Anytime Offices Pty Ltd provides notice to you of our Privacy Policy and practices and of the choices you can make about the way your information is collected online and how that information is used. Please read this Privacy Policy carefully and revisit this page from time to time to review any changes that may have been made.
                        Anytime Offices may amend this Privacy Policy at any time by posting the amended terms on this site. All amended terms automatically take effect on the date set out in the posted Privacy Policy, unless otherwise specified.
                        <h4>Sites covered by this Privacy Policy</h4>
                        This Privacy Policy applies to all Regus owned websites and domains. The Anytime Offices Websites may provide links to third-party websites for your convenience and information. If you access those links, you will leave the Anytime Offices Websites. We do not control those sites or their privacy practices, which may differ from our own privacy practices. This Privacy Policy does not cover any personal data that you choose to give to unrelated third parties. We do not monitor or control the information collected by such sites or the privacy practices of any third parties, and we are not responsible for their practices or the content of their sites.

                        <h4>Types of information we collect and use</h4>
                        In this policy, “personal information” or “personal data” means information about an identifiable individual that is subject to protection under the law in the jurisdiction in which you reside. In some jurisdictions, “personal information” or “personal data” will not include business contact information.
                        Anytime Offices Website collects information through a variety of different ways and for different purposes. If you choose to register with Anytime Offices Websites, then you will be requested to provide contact information (name, address, telephone number, email address, a unique login name, and password). We use this information to contact you about the services on our site in which you have expressed interest. We may also use your contact information to send you information about other Anytime Offices products and services as well as promotional material that may be of interest to you from some of our marketing partners. If you do not want to receive these promotional announcements, you may opt-out when you provide us with contact information or at any time after you register by updating your preferences (see the Opt-Out section below).
                        You also have the option to provide demographic information (such as type of business, size of business, locations, etc.). Anytime Offices uses this demographic information to understand your needs and interests and to provide you a more personalized experience on our site. The information is used by Anytime Offices to process your orders, enable participation in promotions, and facilitate your relationship with us.
                        Through Anytime Offices Websites, you can order products or services, request information, or subscribe to marketing or support materials. In order to purchase a product or service from us, we will request certain information from you. You will need to provide contact information (such as name, email and shipping address) and financial information (such as credit card number, billing address, and expiration date). Financial information collected from you is used only to bill you for the products and services that you have purchased.
                        If we collect credit card information from you, we only use this information for payment processing and fraud prevention. Credit card information and other similar sensitive personal data are not used for any other purpose by Anytime Offices without your express consent. We do not retain your credit card information after processing a payment unless you grant us permission to retain your credit card information for future purchases.
                        In most cases, you provide us with your consent to use your personal data in accordance with this policy by providing us with that information. In some cases, we may specifically ask for your express consent if we believe that the information is sensitive or our use of the information may include other uses not covered by this Privacy Policy or another privacy notice to which we have made available to you.
                        Anytime Offices Websites automatically collects technical information about your visit (such as browser type, Internet service provider, platform type, internet protocol (IP) addresses, referring/exit pages, operating system, date/time stamp). We do not associate this information with other information about you. We aggregate this information for reporting about Anytime Offices Websites to analyse trends, diagnose problems with our server and administer Anytime Offices Website, to track user movement and use, and to gather broad demographic information.
                        <h4>Communications from Anytime Offices</h4>
                        Once you register, we will send you a welcoming email to verify your username and password. We will also respond to your inquiries, provide services you request and manage your account. We will communicate with you by email or telephone and will make every effort to honour your preference.
                        We will also send you information on new products, services, special savings, promotions and general information. If you do not want to receive this information, you can opt-out of receiving future mailings (see Opt-Out section below).
                        If you wish to subscribe to our newsletters, we will use your name and email address to send the newsletter to you. You can sign up for these newsletters from us on our registration page. You may unsubscribe at any time (see Opt-Out section below).
                        When necessary, Anytime Offices will send you service-related announcements, which are not promotional in nature. If you do not wish to receive them, you may deactivate your account with Anytime Offices Website.
                        Please note that we do not provide your email address to our business partners. However, we may send you offers on behalf of our business partners. You can opt out from receiving email offers from Anytime Offices as described below.
                        Sharing of information and Cross-border Transfers
                        Anytime Offices contracts with third-party service providers and suppliers to deliver complete products, services and customer solutions described above. These service providers may change or we may contract with additional service providers to better accommodate our customers. Anytime Offices affiliates may provide services to you or to your local Anytime Offices affiliate and may receive personal data about you. If we transfer your personal data to affiliates or third parties, we require the recipients of your personal data to safeguard your personal data using administrative,
                    </div>
                </section>
            </div>

        </div>
    </div>
</section>
<!-- End About -->
