<style>
    .container2 {
        background-color: #E0E0E0;
        padding-right: 15px;
        padding-left: 15px;
        margin-right: auto;
        margin-left: auto;
    }
</style>

<!--Start revolution-slider-->
<section id="revolution">
    <div class="fullwidthbanner-container revolution-slider">
        <div id="fullwidthbanner">
            <ul>

                <!-- slider 1 -->
                <li data-transition="random" data-slotamount="7" data-masterspeed="1000" data-thumb="assets/images/1920x800.jpg"  data-saveperformance="on">
                    <img src="assets/images/1920x800.jpg"  alt="image" data-lazyload="assets/images/999.jpg" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                    <div class="overlay"></div>

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption randomrotate" data-x="295" data-y="210" data-speed="300" data-start="2000" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 10;"><img src="assets/images/line2.png" alt="image">
                    </div>

                    <!-- LAYER NR. 2 -->
                    <div class="tp-caption lfl" data-x="120" data-y="215" data-speed="300" data-start="2900" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 12;"><h1> <span> ANYTIME OFFICES </span></h1>
                    </div>

                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption large_bold_white_medium lfb tp-resizeme" data-x="300" data-y="190" data-speed="1000" data-start="3200" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 13; max-width: auto; max-height: auto; white-space: nowrap;">FLEXIBLE SPACES</div>

                    <!-- LAYER NR. 4 -->
                    <div class="tp-caption lfb txt" data-x="320" data-y="320" data-speed="1000" data-start="2000" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-endspeed="300" style="z-index: 10; max-width: auto; max-height: auto; white-space: nowrap;border:0px solid #fefefe;"><p><a href="/contactus" class="hvr-wobble-skew">ENQUIRE NOW</a></p>
                    </div>

                </li>

                <!-- slider 1 -->
                <li data-transition="random" data-slotamount="7" data-masterspeed="1000" data-thumb="assets/images/1920x800.jpg"  data-saveperformance="on">
                    <img src="assets/images/1920x800.jpg"  alt="image" data-lazyload="assets/images/1.jpg" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                    <div class="overlay"></div>

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption randomrotate" data-x="295" data-y="210" data-speed="300" data-start="2000" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 10;"><img src="assets/images/line2.png" alt="image">
                    </div>

                    <!-- LAYER NR. 2 -->
                    <div class="tp-caption lfl" data-x="120" data-y="215" data-speed="300" data-start="2900" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 12;"><h1> <span> $90 PER WEEK </span></h1>
                    </div>

                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption large_bold_white_medium lfb tp-resizeme" data-x="300" data-y="190" data-speed="1000" data-start="3200" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 13; max-width: auto; max-height: auto; white-space: nowrap;">SERVICED OFFICES FROM</div>


                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption large_bold_white_medium lfb tp-resizeme" data-x="300" data-y="280" data-speed="1000" data-start="3200" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 13; max-width: auto; max-height: auto; white-space: nowrap;">per person</div>

                    <!-- LAYER NR. 4 -->
                    <div class="tp-caption lfb txt" data-x="320" data-y="320" data-speed="1000" data-start="2000" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-endspeed="300" style="z-index: 10; max-width: auto; max-height: auto; white-space: nowrap;border:0px solid #fefefe;"><p><a href="/contactus" class="hvr-wobble-skew">ENQUIRE NOW</a></p>
                    </div>

                </li>

                <!-- slider 1 -->
                <li data-transition="random" data-slotamount="7" data-masterspeed="1000" data-thumb="assets/images/1920x800.jpg"  data-saveperformance="on">
                    <img src="assets/images/1920x800.jpg"  alt="image" data-lazyload="assets/images/2002.jpg" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                    <div class="overlay"></div>

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption randomrotate" data-x="295" data-y="210" data-speed="300" data-start="2000" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 10;"><img src="assets/images/line2.png" alt="image">
                    </div>

                    <!-- LAYER NR. 2 -->
                    <div class="tp-caption lfl" data-x="120" data-y="215" data-speed="300" data-start="2900" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 12;"><h1>$35 <span>PER WEEK</span></h1>
                    </div>

                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption large_bold_white_medium lfb tp-resizeme" data-x="300" data-y="190" data-speed="1000" data-start="3200" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 13; max-width: auto; max-height: auto; white-space: nowrap;">TELEPHONE ANSWERING AND MAIL HANDLING SERVICE FROM</div>

                    <!-- LAYER NR. 4 -->
                    <div class="tp-caption lfb txt" data-x="320" data-y="320" data-speed="1000" data-start="2000" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-endspeed="300" style="z-index: 10; max-width: auto; max-height: auto; white-space: nowrap;border:0px solid #fefefe;"><p><a href="/contactus" class="hvr-wobble-skew">ENQUIRE NOW</a></p>
                    </div>

                </li>


                <!-- slider 1 -->
                <li data-transition="random" data-slotamount="7" data-masterspeed="1000" data-thumb="assets/images/1920x800.jpg"  data-saveperformance="on">
                    <img src="assets/images/1920x800.jpg"  alt="image" data-lazyload="assets/images/333.jpg" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                    <div class="overlay"></div>

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption randomrotate" data-x="295" data-y="210" data-speed="300" data-start="2000" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 10;"><img src="assets/images/line2.png" alt="image">
                    </div>

                    <!-- LAYER NR. 2 -->
                    <div class="tp-caption lfl" data-x="120" data-y="215" data-speed="300" data-start="2900" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 12;"><h1>get <span>2 MONTHS FREE</span> rent</h1>
                    </div>

                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption large_bold_white_medium lfb tp-resizeme" data-x="300" data-y="190" data-speed="1000" data-start="3200" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 13; max-width: auto; max-height: auto; white-space: nowrap;">CALL US NOW TO TAKE ADVANTAGE OF THIS OFFER</div>

                    <!-- LAYER NR. 4 -->
                    <div class="tp-caption lfb txt" data-x="320" data-y="320" data-speed="1000" data-start="2000" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-endspeed="300" style="z-index: 10; max-width: auto; max-height: auto; white-space: nowrap;border:0px solid #fefefe;"><p><a href="/contactus" class="hvr-wobble-skew">ENQUIRE NOW</a></p>
                    </div>

                </li>


            </ul>
        </div>
    </div>
</section><!--#revolution-->
<!--End slider section-->


<!-- Start About -->
<section id="about">
    <div class="about">
        <div class="container">
            <div class="about-us">
                <a name="solutions"></a>
                <h1>OFFICES</h1>
                <p>LET US TAKE CARE OF YOUR WORKSPACE NEEDS GIVING YOU OPPORTUNITY FOCUS ON GROWING.</p>
                <div class="a-us">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="au-img"><img src="assets/images/IMAGE5.jpg" alt="image" /></div>
                        </div>
                        <div class="col-md-6">
                            <h5><p>We offer selection of private office suites designed to accommodate 1-10 people.</p></h5>

                            <p>All monthly expenses associated with traditional office space are taken care of giving you more time to focus on growing your business.</p>

                            <p>Our offices are tastefully set up with quality furniture and are equipped with latest technology. You will also benefit from access to kitchen amenities and self-service admin areas. In addition, our team are on hand should you need PA support. OUR .</p>
                            <div class="au-icon"><a href="/servicesoffices">Read more</a></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- End About -->


<!-- Start About -->
<section id="about">
    <div class="about">
        <div class="container">
            <div class="about-us">
                <h1>Virtual Offices</h1>
                <div class="a-us">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="au-img"><img src="assets/images/aaaaa.png" alt="image" /></div>
                        </div>
                        <div class="col-md-6">
                            <h5><p>We have a variety of Virtual Office Solutions to suit all budgets and business.</p></h5>

                            <p>We will act as an extension of your business. We can answer your phone calls, handle messages and forward, incoming post required.</p>

                            <p>You will benefit from access to our facilieties including meetings rooms, videoconferencing and day offices and register your businesss address with us.</p>
                            <div class="au-icon"><a href="/virtualoffices">Read more</a></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- End About -->

<!-- Start About -->
<section id="about">
    <div class="about">
        <div class="container">
            <div class="about-us">
                <h1>Meetings rooms</h1>
                <div class="a-us">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="au-img"><img src="assets/images/4sacled.png" alt="image" /></div>
                        </div>
                        <div class="col-md-6">
                            <h5><p>We have a selection of meeting room and boardroom facilities available to book.</p></h5>

                            <p>Our rooms are equiped with conferencing equipment and stationary.</p>
                            <p>You are welcome to use our WiFi, kitchen and amenities.</p>
                            <p>You can also order working lunch and tea coffee service.</p>

                            <p>We also have purpose built videoconferencing suite with great accosutics and additional sound proofing.</p>
                            <a href="/dayoffice">Read more</a></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

<!-- Start About -->
<section id="about">
    <div class="about">
        <div class="container">
            <div class="about-us">
                <h1>Day Offices</h1>
                <div class="a-us">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="au-img"><img src="assets/images/image8.jpg" alt="image" /></div>
                        </div>
                        <div class="col-md-6">
                            <h5><p>We have a selection of day offices, team rooms and consultation rooms available</p></h5>

                            <p>WiFi and access to kitchen amenities included in rate</p>
                            <p>Our front desk team will meet and great your visitors and will provide support with your admin and catering requirements if required.</p>

                            <a href="/dayoffice">Read more</a></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>