<style>
    .container2 {
        background-color: #E0E0E0;
        padding-right: 15px;
        padding-left: 15px;
        margin-right: auto;
        margin-left: auto;
    }

    .space {
        margin-top: 30px;
    }
    .homemenu{
        background:#222;
    }
    .homemenu2{
        background:white;
    }
    .menubox{
        border-color: white;
        border-width: 3px;
        height: 80px;
        text-align: center;
        vertical-align: middle;
        border-style: solid;

    }

    .menubox h3{
        font-size: 20px;
        color: white;
    }

    .menubox2{
        text-align: center;

    }

    .menubox2 h4{
        font-size: 16px;
        color: black;
    }
</style>

<!--Start revolution-slider-->
<section id="revolution">
    <div class="fullwidthbanner-container revolution-slider">
        <div id="fullwidthbanner">
            <ul>

                <!-- slider 1 -->
                <li data-transition="random" data-slotamount="7" data-masterspeed="1000" data-thumb="assets/images/1920x800.jpg"  data-saveperformance="on">
                    <img src="assets/images/1920x800.jpg"  alt="image" data-lazyload="assets/images/999.jpg" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                    <div class="overlay"></div>

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption randomrotate" data-x="295" data-y="210" data-speed="300" data-start="2000" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 10;"><img src="assets/images/line2.png" alt="image">
                    </div>

                    <!-- LAYER NR. 2 -->
                    <div class="tp-caption lfl" data-x="120" data-y="215" data-speed="300" data-start="2900" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 12;"><h1> <span> ANYTIME OFFICES </span></h1>
                    </div>

                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption large_bold_white_medium lfb tp-resizeme" data-x="300" data-y="190" data-speed="1000" data-start="3200" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 13; max-width: auto; max-height: auto; white-space: nowrap;">WHERE DO YOU DO YOUR BEST WORK?</div>

                    <!-- LAYER NR. 4 -->
                    <div class="tp-caption lfb txt" data-x="320" data-y="320" data-speed="1000" data-start="2000" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-endspeed="300" style="z-index: 10; max-width: auto; max-height: auto; white-space: nowrap;border:0px solid #fefefe;"><p><a href="/contactus" class="hvr-wobble-skew">ENQUIRE NOW</a></p>
                    </div>

                </li>

                <!-- slider 1 -->
                <li data-transition="random" data-slotamount="7" data-masterspeed="1000" data-thumb="assets/images/1920x800.jpg"  data-saveperformance="on">
                    <img src="assets/images/1920x800.jpg"  alt="image" data-lazyload="assets/images/1.jpg" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                    <div class="overlay"></div>

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption randomrotate" data-x="295" data-y="210" data-speed="300" data-start="2000" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 10;"><img src="assets/images/line2.png" alt="image">
                    </div>

                    <!-- LAYER NR. 2 -->
                    <div class="tp-caption lfl" data-x="120" data-y="215" data-speed="300" data-start="2900" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 12;"><h1> <span> $90 PER WEEK </span></h1>
                    </div>

                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption large_bold_white_medium lfb tp-resizeme" data-x="300" data-y="190" data-speed="1000" data-start="3200" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 13; max-width: auto; max-height: auto; white-space: nowrap;">SERVICED OFFICES FROM</div>


                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption large_bold_white_medium lfb tp-resizeme" data-x="300" data-y="280" data-speed="1000" data-start="3200" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 13; max-width: auto; max-height: auto; white-space: nowrap;">per person</div>

                    <!-- LAYER NR. 4 -->
                    <div class="tp-caption lfb txt" data-x="320" data-y="320" data-speed="1000" data-start="2000" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-endspeed="300" style="z-index: 10; max-width: auto; max-height: auto; white-space: nowrap;border:0px solid #fefefe;"><p><a href="/contactus" class="hvr-wobble-skew">ENQUIRE NOW</a></p>
                    </div>

                </li>

                <!-- slider 1 -->
                <li data-transition="random" data-slotamount="7" data-masterspeed="1000" data-thumb="assets/images/1920x800.jpg"  data-saveperformance="on">
                    <img src="assets/images/1920x800.jpg"  alt="image" data-lazyload="assets/images/2002.jpg" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                    <div class="overlay"></div>

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption randomrotate" data-x="295" data-y="210" data-speed="300" data-start="2000" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 10;"><img src="assets/images/line2.png" alt="image">
                    </div>

                    <!-- LAYER NR. 2 -->
                    <div class="tp-caption lfl" data-x="120" data-y="215" data-speed="300" data-start="2900" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 12;"><h1><span>$15 PER WEEK</span></h1>
                    </div>

                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption large_bold_white_medium lfb tp-resizeme" data-x="300" data-y="190" data-speed="1000" data-start="3200" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 13; max-width: auto; max-height: auto; white-space: nowrap;">TELEPHONE ANSWERING AND MAIL HANDLING SERVICE FROM</div>

                    <!-- LAYER NR. 4 -->
                    <div class="tp-caption lfb txt" data-x="320" data-y="320" data-speed="1000" data-start="2000" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-endspeed="300" style="z-index: 10; max-width: auto; max-height: auto; white-space: nowrap;border:0px solid #fefefe;"><p><a href="/contactus" class="hvr-wobble-skew">ENQUIRE NOW</a></p>
                    </div>

                </li>


                <!-- slider 1 -->
                <li data-transition="random" data-slotamount="7" data-masterspeed="1000" data-thumb="assets/images/1920x800.jpg"  data-saveperformance="on">
                    <img src="assets/images/1920x800.jpg"  alt="image" data-lazyload="assets/images/333.jpg" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                    <div class="overlay"></div>

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption randomrotate" data-x="295" data-y="210" data-speed="300" data-start="2000" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 10;"><img src="assets/images/line2.png" alt="image">
                    </div>

                    <!-- LAYER NR. 2 -->
                    <div class="tp-caption lfl" data-x="120" data-y="215" data-speed="300" data-start="2900" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 12;"><h1>get <span>2 MONTHS FREE</span> rent</h1>
                    </div>

                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption large_bold_white_medium lfb tp-resizeme" data-x="300" data-y="190" data-speed="1000" data-start="3200" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="8700" data-endspeed="300" style="z-index: 13; max-width: auto; max-height: auto; white-space: nowrap;">CALL US NOW TO TAKE ADVANTAGE OF THIS OFFER</div>

                    <!-- LAYER NR. 4 -->
                    <div class="tp-caption lfb txt" data-x="320" data-y="320" data-speed="1000" data-start="2000" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-endspeed="300" style="z-index: 10; max-width: auto; max-height: auto; white-space: nowrap;border:0px solid #fefefe;"><p><a href="/contactus" class="hvr-wobble-skew">ENQUIRE NOW</a></p>
                    </div>

                </li>

            </ul>
        </div>
    </div>
</section><!--#revolution-->
<!--End slider section-->
<section>
    <div class="homemenu">
        <div class="row">
            <div class="col-md-3 menubox"><h3>WORKSPACE <br>AND PRICING</h3></div>
            <div class="col-md-3 menubox"><h3>RANDWICK</h3></div>
            <div class="col-md-3 menubox"><h3>GET INVOLVED</h3></div>
            <div class="col-md-3 menubox"><h3>CONTACT US</h3></div>
        </div>
    </div>
</section>
<section>
    <div class="homemenu2">
        <div class="row">
            <div class="col-md-3 menubox2">
                <span><h4>Office space</h4></span>
                <span><h4>Virtual Office</h4></span>
                <span><h4>Meeting Room</h4></span>

            </div>
            <div class="col-md-3 menubox2">
                    <span><h4>Location</h4></span>
                    <span><h4>Centre Features</h4></span></div>
            <div class="col-md-3 menubox2">
                <span><h4>Contact details</h4></span>
                <span><h4>Referral program</h4></span>
            </div>
            <div class="col-md-3 menubox2">
                <span><h4>Privacy Policy</h4></span>
                <img src="assets/images/logo-green.gif" width="75">
            </div>
        </div>
    </div>
</section>